# Minimal Travis verfication for salt states
#
# Since salt/salt states aren't a proper language to Travis, this is a
# hackaround for now.
#
# We should probably build a basebox for travis at some point, for the wider
# SaltStack community. (see https://github.com/travis-ci/travis-ci/issues/1549)
language: python
python:
- '2.7'

before_install:
  - sudo apt-get update
  # Install salt master and salt minion on the same box
  - curl -L http://bootstrap.saltstack.org | sudo sh -s -- git develop
  # Set up our installation bits
  - sudo mkdir -p /srv/salt/states
  - sudo cp .travis/minion /etc/salt/minion

install:
  # Copy the states and restart
  - sudo cp -r . /srv/salt/states
  - sudo service salt-minion restart

  # If anything bad happened on restarting the minion,
  # we'll want to see the logs
  - sudo cat /var/log/salt/*

  # For additional debugging, see what's in grains on a travis box
  - sudo salt-call grains.items --local

script:
  # Minimally validate YAML and Jinja at a basic level
  - sudo salt-call state.show_highstate --local --retcode-passthrough
  
  # Full on installation test
  - sudo salt-call state.highstate --local
  
  # Light integration tests to make a real test suite for later
  - wget -S -O - 127.0.0.1:8080 | grep "IPython Notebook Viewer"
  - wget -S -O - 127.0.0.1:8080/github/ipython/ipython/tree/master/examples/notebooks/ | grep "Custom Display Logic.ipynb"
  - wget -S -O rendered.html 127.0.0.1:8080/github/ipython/ipython/blob/master/examples/notebooks/Custom%20Display%20Logic.ipynb
  - grep "Defining Custom Display Logic" rendered.html
